import React, { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, Download, Mail, Calendar, TrendingUp, AlertCircle, Loader2, BarChart3 } from 'lucide-react';
import { Button, Card } from '@components/Common';
import { useAuth } from '@hooks/useAuth';
import { useGetDepartmentStaffQuery } from '@/features/department/department.api';
import { ROUTES } from '@constants/index';
import { showError } from '@/utils/toast';

const DepartmentStaffDetailPage: React.FC = () => {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const { user } = useAuth();
  const [reportType, setReportType] = useState<'detailed' | 'summary'>('detailed');

  const { data: staffResponse, isLoading, isError } = useGetDepartmentStaffQuery(
    user?.departmentId || ''
  );

  const staff = staffResponse?.data?.find((s: any) => s._id === id);

  const generateIndividualReport = (type: 'detailed' | 'summary') => {
    if (!staff) return;

    const timestamp = new Date().toLocaleString();
    const report = type === 'detailed' 
      ? generateDetailedReport(staff, timestamp)
      : generateSummaryReport(staff, timestamp);

    downloadReport(report, `staff-report-${staff.profile?.fullName || id}-${Date.now()}`);
  };

  const generateDetailedReport = (staffMember: any, timestamp: string) => {
    return `
DETAILED STAFF PERFORMANCE REPORT
Generated: ${timestamp}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

EMPLOYEE INFORMATION
Name: ${staffMember.profile?.fullName}
Email: ${staffMember.email}
Rank: ${staffMember.rank || 'N/A'}
Status: ${staffMember.accountStatus}
Account Created: ${new Date(staffMember.createdAt).toLocaleDateString()}

PERFORMANCE METRICS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Complaints Assigned: ${staffMember.stats?.assignedCount || 0}
Complaints Resolved: ${staffMember.stats?.resolvedCount || 0}
Resolution Rate: ${staffMember.stats?.assignedCount > 0 
  ? ((staffMember.stats?.resolvedCount / staffMember.stats?.assignedCount) * 100).toFixed(2) 
  : 0}%
Compliance Rate: ${(staffMember.stats?.complianceRate || 0).toFixed(2)}%
SLA Breaches: ${staffMember.stats?.slaBreaches || 0}
Last Activity: ${staffMember.stats?.lastActivityAt 
  ? new Date(staffMember.stats?.lastActivityAt).toLocaleDateString()
  : 'N/A'}

PERFORMANCE ANALYSIS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${staffMember.stats?.resolvedCount > 10 ? '✓ High productivity level' : '⚠ Productivity below average'}
${staffMember.stats?.complianceRate > 85 ? '✓ Good compliance rate' : '⚠ Compliance needs improvement'}
${staffMember.stats?.slaBreaches === 0 ? '✓ No SLA breaches' : '⚠ Has SLA breaches that need attention'}

RECOMMENDATIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${generateRecommendations(staffMember).join('\n')}

Report Generated by Department Management System
    `;
  };

  const generateSummaryReport = (staffMember: any, timestamp: string) => {
    return `
STAFF PERFORMANCE SUMMARY
Generated: ${timestamp}

${staffMember.profile?.fullName}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Resolved: ${staffMember.stats?.resolvedCount || 0}
Compliance: ${(staffMember.stats?.complianceRate || 0).toFixed(2)}%
SLA Breaches: ${staffMember.stats?.slaBreaches || 0}
Status: ${staffMember.accountStatus}
    `;
  };

  const generateRecommendations = (staffMember: any): string[] => {
    const recs: string[] = [];
    
    if ((staffMember.stats?.resolvedCount || 0) < 5) {
      recs.push('• Increase complaint resolution efforts');
    }
    if ((staffMember.stats?.complianceRate || 0) < 80) {
      recs.push('• Compliance rate below target - training recommended');
    }
    if ((staffMember.stats?.slaBreaches || 0) > 2) {
      recs.push('• Multiple SLA breaches - review workload allocation');
    }
    if (recs.length === 0) {
      recs.push('• Excellent performance - maintain current standards');
    }
    
    return recs;
  };

  const downloadReport = (content: string, filename: string) => {
    const element = document.createElement('a');
    element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(content));
    element.setAttribute('download', `${filename}.txt`);
    element.style.display = 'none';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  if (isLoading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[500px]">
        <Loader2 className="w-12 h-12 animate-spin text-blue-600 mb-4" />
        <p className="text-slate-500 font-medium">Loading staff details...</p>
      </div>
    );
  }

  if (!staff) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[500px]">
        <AlertCircle className="w-12 h-12 text-red-500 mb-4" />
        <h3 className="text-xl font-bold text-slate-800 mb-2">Staff member not found</h3>
        <Button 
          variant="outline" 
          className="mt-6" 
          onClick={() => navigate(ROUTES.DEPARTMENT_STAFF_PERFORMANCE)}
        >
          Back to Staff Performance
        </Button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center gap-4">
        <button
          onClick={() => navigate(ROUTES.DEPARTMENT_STAFF_PERFORMANCE)}
          className="p-2 hover:bg-secondary-100 rounded-lg transition-colors"
        >
          <ArrowLeft className="w-6 h-6 text-secondary-600" />
        </button>
        <div className="flex-1">
          <h1 className="text-3xl font-bold text-secondary-900">{staff.profile?.fullName}</h1>
          <p className="text-secondary-600 mt-1">{staff.email}</p>
        </div>
      </div>

      {/* Staff Overview */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card variant="md" className="p-6">
          <div className="flex items-center gap-3 mb-3">
            <div className="p-2 bg-blue-100 rounded-lg">
              <BarChart3 className="w-5 h-5 text-blue-600" />
            </div>
            <span className="text-sm text-secondary-600">Rank</span>
          </div>
          <p className="text-2xl font-bold text-secondary-900 capitalize">{staff.rank || 'Staff'}</p>
        </Card>

        <Card variant="md" className="p-6">
          <div className="flex items-center gap-3 mb-3">
            <div className="p-2 bg-green-100 rounded-lg">
              <TrendingUp className="w-5 h-5 text-green-600" />
            </div>
            <span className="text-sm text-secondary-600">Account Status</span>
          </div>
          <p className="text-2xl font-bold text-secondary-900 capitalize">{staff.accountStatus}</p>
        </Card>

        <Card variant="md" className="p-6">
          <div className="flex items-center gap-3 mb-3">
            <div className="p-2 bg-purple-100 rounded-lg">
              <Calendar className="w-5 h-5 text-purple-600" />
            </div>
            <span className="text-sm text-secondary-600">Joined</span>
          </div>
          <p className="text-xl font-bold text-secondary-900">{new Date(staff.createdAt).toLocaleDateString()}</p>
        </Card>

        <Card variant="md" className="p-6">
          <div className="flex items-center gap-3 mb-3">
            <div className="p-2 bg-amber-100 rounded-lg">
              <Mail className="w-5 h-5 text-amber-600" />
            </div>
            <span className="text-sm text-secondary-600">Last Active</span>
          </div>
          <p className="text-sm font-bold text-secondary-900">
            {staff.stats?.lastActivityAt 
              ? new Date(staff.stats?.lastActivityAt).toLocaleDateString()
              : 'N/A'}
          </p>
        </Card>
      </div>

      {/* Performance Metrics */}
      <Card variant="md" className="p-6">
        <h2 className="text-xl font-bold text-secondary-900 mb-6">Performance Metrics</h2>
        
        <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
          <div className="text-center">
            <div className="text-4xl font-bold text-blue-600 mb-2">
              {staff.stats?.assignedCount || 0}
            </div>
            <p className="text-sm text-secondary-600">Complaints Assigned</p>
          </div>

          <div className="text-center">
            <div className="text-4xl font-bold text-green-600 mb-2">
              {staff.stats?.resolvedCount || 0}
            </div>
            <p className="text-sm text-secondary-600">Resolved</p>
          </div>

          <div className="text-center">
            <div className="text-4xl font-bold text-purple-600 mb-2">
              {(staff.stats?.complianceRate || 0).toFixed(1)}%
            </div>
            <p className="text-sm text-secondary-600">Compliance Rate</p>
          </div>

          <div className="text-center">
            <div className={`text-4xl font-bold mb-2 ${(staff.stats?.slaBreaches || 0) > 0 ? 'text-red-600' : 'text-green-600'}`}>
              {staff.stats?.slaBreaches || 0}
            </div>
            <p className="text-sm text-secondary-600">SLA Breaches</p>
          </div>
        </div>

        {staff.stats?.assignedCount > 0 && (
          <div className="mt-6 pt-6 border-t border-secondary-200">
            <p className="text-sm text-secondary-600 mb-2">Resolution Rate</p>
            <div className="w-full bg-secondary-200 rounded-full h-3 overflow-hidden">
              <div 
                className="bg-gradient-to-r from-blue-500 to-green-500 h-full"
                style={{
                  width: `${((staff.stats?.resolvedCount / staff.stats?.assignedCount) * 100)}%`
                }}
              />
            </div>
            <p className="text-sm text-secondary-600 mt-2">
              {((staff.stats?.resolvedCount / staff.stats?.assignedCount) * 100).toFixed(1)}% Complete
            </p>
          </div>
        )}
      </Card>

      {/* Report Generation */}
      <Card variant="md" className="p-6 bg-gradient-to-r from-blue-50 to-indigo-50">
        <h2 className="text-xl font-bold text-secondary-900 mb-4">Generate Report</h2>
        
        <div className="space-y-4">
          <p className="text-secondary-700">
            Generate a performance report for {staff.profile?.fullName}. Choose the report type:
          </p>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Card variant="md" className="p-4 border-2 border-blue-200 cursor-pointer hover:shadow-md transition-shadow"
              onClick={() => setReportType('detailed')}
            >
              <input 
                type="radio" 
                checked={reportType === 'detailed'}
                onChange={() => setReportType('detailed')}
                className="mr-2"
              />
              <label className="font-semibold text-secondary-900">Detailed Report</label>
              <p className="text-xs text-secondary-600 mt-2">
                Complete performance analysis with recommendations
              </p>
            </Card>

            <Card variant="md" className="p-4 border-2 border-green-200 cursor-pointer hover:shadow-md transition-shadow"
              onClick={() => setReportType('summary')}
            >
              <input 
                type="radio" 
                checked={reportType === 'summary'}
                onChange={() => setReportType('summary')}
                className="mr-2"
              />
              <label className="font-semibold text-secondary-900">Summary Report</label>
              <p className="text-xs text-secondary-600 mt-2">
                Quick overview of key metrics
              </p>
            </Card>
          </div>

          <Button
            variant="primary"
            onClick={() => generateIndividualReport(reportType)}
            icon={<Download className="w-4 h-4" />}
          >
            Download {reportType === 'detailed' ? 'Detailed' : 'Summary'} Report
          </Button>
        </div>
      </Card>

      {/* Performance Assessment */}
      <Card variant="md" className="p-6">
        <h2 className="text-lg font-bold text-secondary-900 mb-4">Performance Assessment</h2>
        
        <div className="space-y-3">
          {generateRecommendations(staff).map((rec, idx) => (
            <div key={idx} className="flex items-start gap-3 p-3 bg-secondary-50 rounded-lg">
              <span className="text-blue-600 font-bold flex-shrink-0">→</span>
              <span className="text-secondary-700">{rec}</span>
            </div>
          ))}
        </div>
      </Card>
    </div>
  );
};

export default DepartmentStaffDetailPage;
